# Generated by Django 5.1.1 on 2024-09-16 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_order_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_signature',
        ),
    ]
